In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
def predict_func(slope,intercept,x_test):
    #
    #pred = []
    #n_data = x_test.shape[0]
    #x_test.values.tolist()
    #for i in range(n_data):
    #    pred.append(((slope * x_test[i]) + intercept).tolist)
    #temp = np.dot(slope, x_test.T)
    pred = ((np.dot(x_test, slope)) + intercept)
        
    return pred

In [3]:
def mse_calc(prediction, y_test):
    #
    #total_data = len(prediction)
    #error = 0
    error = np.mean((prediction - y_test)**2)
    return error

In [4]:
#gradient descent 
def grad_descent(s_theta, l_rate, tolerance, iter_val, x_train, y_train):
    
    n_data = len(x_train)
    bias = np.ones((n_data,1))
    s_intercept = s_theta[0]
    s_slope = s_theta[1:]
    prediction = predict_func(s_slope, s_intercept, x_train)
    error =  mse_calc(prediction, y_train)
    x_train_b = np.append(bias, x_train, axis = 1) 
    
    for i in range(iter_val):
        int_theta = [0 for i in range(len(x_train[0]) + 1)]
        #int_intercept = 0
        n_pt = float(len(x_train))
        
        prediction = predict_func(s_slope, s_intercept, x_train)
        #prev_error = error
        #for i in range(len(x_train)):
        
        #int_intercept = 2 / n_pt * np.dot(bias.T, (prediction - y_train))
        #int_slope = 2 / n_pt * np.dot(x_train.T, (prediction - y_train))
        
        int_theta = 2 / n_pt * np.dot(x_train_b.T, (prediction - y_train))
            
        #final_slope = s_slope - (l_rate * int_slope)
        #final_intercept = s_intercept - (l_rate * int_intercept)
        #s_slope = final_slope
        #s_intercept = final_intercept
        
        s_theta -=  l_rate * int_theta
        
        #prediction = predict_func(s_slope, s_intercept, x_train)
        #error = mse_calc(prediction, y_train)
        
        #if ((prev_error - error) / prev_error) <= tolerance:
        #    break
        
    s_intercept = s_theta[0]
    s_slope = s_theta[1:]
    prediction = predict_func(s_slope, s_intercept, x_train)
    final_error = mse_calc(prediction, y_train)
        
    return  s_theta, final_error

In [5]:
X = 2 * np.random.rand(100,1)
y = 4 +3 * X+np.random.randn(100,1)
#X

In [6]:
theta = np.zeros((len(X[0]) + 1, 1))
tolerance = 0.0001
l_rate = 0.01
iterations = 5000

In [7]:
theta

array([[0.],
       [0.]])

In [8]:
grad_theta, grad_error = grad_descent(theta, l_rate, tolerance, iterations, X, y)
grad_theta, grad_error

(array([[4.34150855],
        [2.79426428]]), 0.8919455707231276)

In [9]:
n_data = len(X)
bias = np.ones((n_data,1))

x_train_b = np.append(bias, X, axis = 1)
#x_train_b

In [10]:
prediction = predict_func(theta[1:], theta[0], X)
#prediction
(prediction - y).T


array([[-0.82329931,  0.34106755,  0.54567317,  0.25187904,  0.22732885,
        -0.62903548,  2.02030147,  0.64707023,  0.1650837 , -0.10274553,
         0.3396132 ,  1.14240643,  1.32389095,  0.29527514,  1.79792895,
         0.09259919,  0.31470144,  0.35626605, -0.15452033, -0.51496652,
         0.46109327,  0.47171778, -0.64275828,  0.80322562, -0.79512756,
        -1.58962694,  0.79180473, -0.63930693,  1.3601015 , -0.02546762,
         0.41011607,  1.08923101,  2.19964684, -1.17249519, -0.75623183,
         0.062467  ,  0.94562835, -0.14922936,  1.17108711, -0.7112326 ,
         0.31733955, -1.14230264,  0.58676363,  0.89073518, -0.58668904,
        -0.38631142, -0.74117568, -0.80488802, -1.61717178, -1.61522345,
         1.50905098,  1.7289428 , -0.7483806 , -0.82816183, -1.01096325,
        -0.31226569, -0.33625871, -1.2499783 , -0.67922158,  1.23694614,
         0.26695252,  0.36769701,  0.38777116, -0.2523876 ,  0.6208753 ,
        -0.34033515, -0.87925623, -0.86276459,  0.7

In [11]:
int_theta = 1 / (2*n_data) * np.dot(x_train_b.T, (prediction - y))
int_theta * l_rate
theta - int_theta * l_rate

array([[4.34150855],
       [2.79426428]])