## Solutions to LAST WEEK's Mini-Challenges:

<img src="../images/icon/ppt-icons.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

### Mini Challenge - 1
***
Can you write a function square_root having default value of input a=9 and find the square-root of the same.

In [1]:
import math
def square_root(a=9):
    return math.sqrt(a)

c = square_root()
c

3.0

<img src="../images/icon/ppt-icons.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />
### Mini Challenge - 2
***
Can you write a function function_tuple that takes in two numbers a and b and returns the sum as well as the product of these numbers

In [2]:
def function_tuple(a=0,b=0):
    return a+b,a*b

c = function_tuple(10,20)
c

(30, 200)

<img src="../images/icon/ppt-icons.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />
### Mini Challenge - 3
***
Can you write a lambda function to add two numbers a and b. 

In [1]:
lambda_sum = lambda x,y:x+y
lambda_sum(10,20)

30

<img src="../images/icon/ppt-icons.png" alt="ppt-icons" style="width: 100px;float:left; margin-right:15px"/>
<br />
***
## Mini Challenge - 4  :  
***
Create a matrix from the list of lists [[5.3, 10.2, 15.1], [20.4, 25.3, 30.9], [35.4, 40.1,45.6]]. Print the dtype and shape. 

In [4]:
import numpy as np
l = np.matrix([[5.3, 10.2, 15.1], [20.4, 25.3, 30.9], [35.4, 40.1,45.6]])

print(l)
print()
print(l.dtype)
print()
print(l.shape)

[[ 5.3 10.2 15.1]
 [20.4 25.3 30.9]
 [35.4 40.1 45.6]]

float64

(3, 3)


<img src="../images/icon/ppt-icons.png" alt="ppt-icons" style="width: 100px;float:left; margin-right:15px"/>
<br />
## Mini Challenge - 5 : 
***
Create an ndimensional array from randomly genrated numbers of shape (3,4), then rehape the array to (4,3)


In [5]:
Array = np.random.rand(3,4)
print(Array)
print()
print(Array.reshape(4,3))

[[0.59436288 0.55245813 0.92988836 0.8709026 ]
 [0.91638806 0.74395395 0.82312241 0.46064196]
 [0.5485115  0.07414473 0.58599068 0.64060117]]

[[0.59436288 0.55245813 0.92988836]
 [0.8709026  0.91638806 0.74395395]
 [0.82312241 0.46064196 0.5485115 ]
 [0.07414473 0.58599068 0.64060117]]
